[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "functions/"
  included_files = ["data/**"]

[template.environment]
  TWITCH_CLIENT_ID = "Twitch client id"
  TWITCH_CLIENT_SECRET = "Twitch client secret"